### ISSUE TITLE
Add difference handleSession and startSession

### ISSUE THREAD

**Issue by ivard** [privacybydesign/irma-frontend-packages#12]
Now only a `start` function is defined (having the behaviour of the `startSession`), but we also need a `handleSession` equivalent to start sessions where a QR is already generated for at the back-end.

**Comment by Timendus** [comment]
My suggestion, as discussed on Slack, is to deprecate that feature in favour of more flexible server communication.

If your application back-end serves just one session and that's it, we can't restart the session from the user interface. That means: every time the user makes a mistake or waits too long, or whatever, we have to disappoint them and/or reload the whole page. That makes no sense to me.

Especially when it's so simple to give `irma-server` an endpoint where it can request new sessions through your application back-end to its hearts desire.

I've been working on these explainer diagrams:

![IRMA diagrams 001](https://user-images.githubusercontent.com/2649939/70380228-0589c780-1938-11ea-898a-d7e49b6b1daa.png)

You web browser requests the web page from your server. With the old `handleSession` this step would already request a session on the IRMA server. We skip that, and instead just serve the web page and the javascripts.

![IRMA diagrams 003](https://user-images.githubusercontent.com/2649939/70380229-09b5e500-1938-11ea-9b86-44a355b9659d.png)

The javascripts (through the more flexible `irma-server` plugin) then request a new session from your application back-end. At this time your back-end talks to IRMA server and starts the required session. The back-end is in full control and the keys and the token and the kind of session are all safe.

![IRMA diagrams 004](https://user-images.githubusercontent.com/2649939/70380232-0c183f00-1938-11ea-852e-f9339aefd4d4.png)

The user goes through the usual stuff, where their phone and their web browser both talk to the IRMA server directly. This is perfectly safe.

![IRMA diagrams 006](https://user-images.githubusercontent.com/2649939/70380233-0f132f80-1938-11ea-98bd-b79e0929ad3a.png)

And finally, the `start` Promise from `irma-core` resolves, and you can handle that in your web page whichever way you want. You probably want to send the user to a new page, or at least do a request to validate that your session succeeded. That's up to the developer, but in that step you can use the token to request the session result.

I think this is a much better "best practice" to be pushing.

Of course, for demo's and quick "getting started" manuals, we can just let the browser communicate with the IRMA server directly, in which case we swap out steps two and four for their "unsafe" (but easy) counterparts:

![IRMA diagrams 002](https://user-images.githubusercontent.com/2649939/70380234-15a1a700-1938-11ea-8744-ab8e1104bf48.png)

![IRMA diagrams 005](https://user-images.githubusercontent.com/2649939/70380238-23572c80-1938-11ea-956b-a064cd1570db.png)

**Comment by ivard** [comment]
These are all sessions that are already started by the back-end and the web browser only receives the QR session pointer. This is therefore equivalent with the current `handleSession`. When I look to the current start, it receives a `request` instead of a `sessionPointer`, so that then mismatches a bit I think?
Furthermore, how would the JWT start session flow work in this set-up then. So I receive a JWT from the back-end application and as web browser I want to start a session by sending the signed JWT to the IRMA server and from the IRMA server I get then back the actual sessionPointer for the QR.

**Comment by Timendus** [comment]
Discussed this in our video meeting, decided to support only these two flows:

1. Back-end signs session body and passes that to front-end. Front-end passed signed body to IRMA server. Front-end can send the same message multiple times to restart the session, but not manipulate the body.
    * Pro: no need to add endpoints in back-end
    * Con: front-end can see disclosed attributes
    * -> Need to add diagrams for this, but very similar to 2a and 4a
2. Front-end asks back-end to start session at IRMA server. Back-end "proxies" request to IRMA server, making sure that the right request is made and if desired that the token doesn't get returned to the front-end.
    * Pro: front-end can't see disclosed attributes, if back-end doesn't want it to
    * Pro: IRMA server can be mostly firewalled off from the outside world
    * Con: need to add endpoints in back-end
    * -> Diagrams 2b and 4b

In both cases, the flow stars with the front-end making a request, as defined by the developer. Both of these we can do with the existing `irma-server` plugin.

So I think we can close this issue?

**Comment by ivard** [comment]
I still make a wrapper that matches the old `irmajs` calls onto the new library, so with that we still remain the two functions for the people that want to stick to the legacy IRMAjs API.
