### ISSUE TITLE
Font doesn't load when using irma-frontend

### ISSUE THREAD

**Issue by Timendus** [privacybydesign/irma-frontend-packages#24]
For some reason the Javascript tries to request the font files from the domain of the hosting webpage, not the domain where the Javascripts came from (and where the fonts live).

![Screenshot 2020-01-20 at 11 55 53](https://user-images.githubusercontent.com/2649939/72721247-df348a00-3b7b-11ea-8863-4208c9c526e6.png)

This results in all the text being rendered in Tahoma or Arial, which is not as pretty.

Quick fix: instruct users of `irma-frontend` to host the font files. Not sure what needs to be done for a "real" fix.

**Comment by ivard** [comment]
The fonts are now included in the bundle. This enlarges the bundle size significanty, but it is a solution. I also switched to a compressed font type to compensate for this again.
