### ISSUE TITLE
Integrate browser fallback functionality to prevent the IRMA app failing to open

### ISSUE THREAD

**Issue by snevas** [privacybydesign/irma-frontend-packages#39]
When trying to load attributes e.g. with DigiD with a alternate default browser set, you could end up with a redirect to the app store webpage. This is because e.g. Firefox does not open app-links by default (privacy measure), which triggers the redirect. This could be solved within the app (WebView), or within the Gemeente Nijmegen-flow.

Version app: 6.0.11
Alternate default browser: Firefox Mobile
Android 10

Steps:
- Open IRMA app
- Voeg meer gegevens toe
- Klik woonadres / persoonsgegevens
- Voeg toe
- Inloggen met DigiD
- You end up with the webview of the irma app, app store webpage.

**Comment by snevas** [comment]
The loading of attibutes functionality (https://services.nijmegen.nl/irma/gemeente/start) works the same from the AngryGames demo.

The the age check has a new/other issue: If I click open app, and approve giving the age proof, I get back to the irma.app-site, but it does not forward me to a passed-page. Should I open another issue for this?

**Comment by ivard** [comment]
If it really contains a bug in the demo itself, then you can indeed better make an issue in [Angrygames](https://github.com/privacybydesign/angrygames) itself. I tested it myself and I don't have any problems, so I'm curious to the bug report to reproduce then. In the Firefox Android app you should enable the setting to open links in other apps (Settings -> enable 'Open links in apps'), to circumvent this current issue `irma-frontend-packages`.
